github.com:
    users:
        mattBrighto:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: mattBrighto
